### ISSUE TITLE
Installation Errorin Ubuntu: HDR5 version already higher than the required version still throwing error

### ISSUE THREAD

**Issue by airwarriorg91** [fschuch/xcompact3d_toolbox#13]
I am trying to install the library using `pip install xcompact3d-toolbox` on ubuntu. I have the latest python version 3.10.6. I am not able to install the library. Can you check what is the problem ?

Error thrown in ubuntu.  have HDF5 installed in my ubuntu. The version of hdf5 is 1.10.7. Even though the installed version higher than the required version, it is throwing this error.
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      /tmp/pip-install-t2d9p96x/netcdf4_cc59d687b3284bc59f45ac26b7c46ba9/setup.py:136: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in Python 3.12. Use ConfigParser directly instead.
        config = configparser.SafeConfigParser()
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t2d9p96x/netcdf4_cc59d687b3284bc59f45ac26b7c46ba9/setup.py", line 224, in <module>
          raise ValueError('HDF5 version >= 1.8.0 is required')
      ValueError: HDF5 version >= 1.8.0 is required
      reading from setup.cfg...
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by airwarriorg91** [comment]
@fschuch Can you please help ?

**Comment by fschuch** [comment]
Hello. This project does not depend on HDF5 directly, but it looks like netcdf4 does. If I remember correctly, HDF5 here refers to the python package, there is no need to install it on the system package manager, but I‘ll double check.

**Comment by airwarriorg91** [comment]
It is trying to install multiple versions of netcdf4 and then failing with the error.

**Comment by fschuch** [comment]
The version of netcdf4 is the only one not specified on the requirements:
https://github.com/fschuch/xcompact3d_toolbox/blob/b1c1acdc47005a59c8d297a50002fc9da3bac736/setup.py#L53

I suspect xcompact3d-toolbox is not compatible with the recent version from there.

**Comment by airwarriorg91** [comment]
Yeah. PyPi is not able to find a compatible version for xcompact3d-toolbox and other dependencies.

**Comment by fschuch** [comment]
The version for `netcdf4` was specified in the new release 1.1.1 for the toolbox. Could you check it the issue persists?
