### ISSUE TITLE
iforces parameter not identified

### ISSUE THREAD

**Issue by airwarriorg91** [fschuch/xcompact3d_toolbox#63]
Hello,
Can you add support for `iforces=1` such that the force calculation around immersed body can be facilitated using the `forces.f90` ? If the parameter is enabled then the force calculation can be done for any flow type. Right now the code doesn't work for the Sphere problem when `itype=5`. If you could point out the required modifications, I can try once.

Edit: xcompact_toolbox doesn't identify the parameter but after the mesh generation for sphere example, if `iforces=1` is added . The force calculation is done. A possible workaround.

Thanks,
Gaurav

**Comment by fschuch** [comment]
Hello @airwarriorg91,

Thanks for letting us know about this issue. This was fixed on release v1.2.1.
